site_name: NetDEM
repo_url: https://github.com/apaam/netdem_docs
site_url: https://apaam.github.io/netdem_docs/
# edit_url: edit/main/docs/

theme:
  name: sandstone
  navigation_depth: 4
  # nav_style: light
  custom_dir: themes/mfem/
  features:
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Examples: examples/index.md
    # - Random packing: examples/random_packing.md
    # - Triaxial compression: examples/triaxial_compression.md
    # - Angle of repose: examples/angle_of_repose.md
    # - Granular mixing: examples/granular_mixing.md
  - Documentation: 
    - User manual: documentation/user_manual.md  
    - Developer manual: documentation/developer_manual.md
    - DEM wiki: documentation/dem_wiki.md
    - Code doxygen: doxygen/html/index.html
  - Download: download/index.md
  - Gallery: 
    - Snapshots: gallery/snapshots.md
    - Animations: gallery/animations.md
  - About:
    - News & Updates: about/news_&_updates.md
    - Help & Support: about/help_&_support.md
    - Publications: about/publications.md
    - Acknowledgements: about/acknowledgement.md  

markdown_extensions: 
  - pymdownx.arithmatex
  - attr_list
  - extra
  - fenced_code  
  - footnotes

plugins:
  - search
  - bibtex:
      bib_file: "docs/refs.bib"
  - mkdocs-video:
      mark: "video-marker"
      css_style:
        width: "50vw"
        height: "57vh"

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'

